/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package recruitment.task.softwaremind;

import static java.lang.Long.parseLong;
import static java.util.stream.Collectors.toCollection;

import java.util.Set;
import java.util.TreeSet;
import java.util.stream.LongStream;
import java.util.stream.Stream;

public class InvoiceApp {
  public static void main(String[] args) {
    InvoiceApp invoiceApp = new InvoiceApp();
    Set<Long> invoices = invoiceApp.invoices(new String[] {"1, 3-5, 4, 9"});
    System.out.println(invoices);
  }

  public Set<Long> invoices(String[] args) {
    String invoices = args[0];

    return Stream.of(invoices.split(","))
        .map(String::trim)
        .flatMap(invoicePages -> {
          if (invoicePages.length() == 3) {
            String startRange = invoicePages.substring(0, 1);
            String endRange = invoicePages.substring(2, 3);
            return LongStream.range(parseLong(startRange), parseLong(endRange) + 1).mapToObj(String::valueOf);
          }
          return Stream.of(invoicePages);
        })
        .map(Long::parseLong).collect(toCollection(TreeSet::new));
  }
}